// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import '../error.dart';
import '../remote_read.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `retry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `read`, `seek`

Future<DetectedFormat> detectFromUrl(
        {required String url, required BlockingHttpClient http}) =>
    RustLib.instance.api
        .crateApiRemoteReadNativeHttpDetectFromUrl(url: url, http: http);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlockingHttpClient>>
abstract class BlockingHttpClient implements RustOpaqueInterface {
  Future<HttpResponse> getAll({required String url});

  Future<HttpResponse> getRange(
      {required String url, required BigInt start, required BigInt end});

  Future<RemoteFileInfo> head({required String url});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<BlockingHttpClient> newInstance() =>
      RustLib.instance.api.crateApiRemoteReadNativeHttpBlockingHttpClientNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RemoteReader>>
abstract class RemoteReader implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<RemoteReader> newInstance(
          {required String url,
          required RemoteFileInfo info,
          required ArcBlockingHttpClient http}) =>
      RustLib.instance.api.crateApiRemoteReadNativeHttpRemoteReaderNew(
          url: url, info: info, http: http);

  Future<Uint8List> readAt({required BigInt offset, required BigInt length});
}
