// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/api.dart';
import 'api/audio_properties.dart';
import 'api/error.dart';
import 'api/picture.dart';
import 'api/tag.dart';
import 'api/tag_changes.dart';
import 'api/tag_field.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 1345647280;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'haudiotagger',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'assets/packages/haudiotagger/pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiApiClear({required String path});

  Future<Uint8List> crateApiApiClearFromBytes({required List<int> bytes});

  Future<Picture> crateApiPicturePictureNew(
      {required PictureType pictureType,
      MimeType? mimeType,
      required List<int> bytes});

  Future<Tag> crateApiApiRead({required String path});

  Future<Tag> crateApiApiReadFromBytes({required List<int> bytes});

  Future<AudioProperties> crateApiAudioPropertiesReadProperties(
      {required String path});

  Future<AudioProperties> crateApiAudioPropertiesReadPropertiesFromBytes(
      {required List<int> bytes});

  Future<void> crateApiApiRemove(
      {required String path, required List<TagField> fields});

  Future<Uint8List> crateApiApiRemoveFromBytes(
      {required List<int> bytes, required List<TagField> fields});

  Future<TagChanges> crateApiTagChangesTagChangesDefault();

  Future<bool> crateApiTagChangesTagChangesIsEmpty({required TagChanges that});

  Future<Tag> crateApiTagTagDefault();

  Future<bool> crateApiTagTagIsEmpty({required Tag that});

  Future<void> crateApiTagChangesUpdate(
      {required String path, required TagChanges changes});

  Future<Uint8List> crateApiTagChangesUpdateFromBytes(
      {required List<int> bytes, required TagChanges changes});

  Future<void> crateApiApiWrite({required String path, required Tag data});

  Future<Uint8List> crateApiApiWriteToBytes(
      {required List<int> bytes, required Tag data});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiApiClear({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiClearConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiClearConstMeta => const TaskConstMeta(
        debugName: "clear",
        argNames: ["path"],
      );

  @override
  Future<Uint8List> crateApiApiClearFromBytes({required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiClearFromBytesConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiClearFromBytesConstMeta => const TaskConstMeta(
        debugName: "clear_from_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<Picture> crateApiPicturePictureNew(
      {required PictureType pictureType,
      MimeType? mimeType,
      required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_picture_type(pictureType, serializer);
        sse_encode_opt_box_autoadd_mime_type(mimeType, serializer);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_picture,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiPicturePictureNewConstMeta,
      argValues: [pictureType, mimeType, bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPicturePictureNewConstMeta => const TaskConstMeta(
        debugName: "picture_new",
        argNames: ["pictureType", "mimeType", "bytes"],
      );

  @override
  Future<Tag> crateApiApiRead({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tag,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiReadConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiReadConstMeta => const TaskConstMeta(
        debugName: "read",
        argNames: ["path"],
      );

  @override
  Future<Tag> crateApiApiReadFromBytes({required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tag,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiReadFromBytesConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiReadFromBytesConstMeta => const TaskConstMeta(
        debugName: "read_from_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<AudioProperties> crateApiAudioPropertiesReadProperties(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_audio_properties,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiAudioPropertiesReadPropertiesConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAudioPropertiesReadPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "read_properties",
        argNames: ["path"],
      );

  @override
  Future<AudioProperties> crateApiAudioPropertiesReadPropertiesFromBytes(
      {required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_audio_properties,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiAudioPropertiesReadPropertiesFromBytesConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAudioPropertiesReadPropertiesFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "read_properties_from_bytes",
        argNames: ["bytes"],
      );

  @override
  Future<void> crateApiApiRemove(
      {required String path, required List<TagField> fields}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_list_tag_field(fields, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiRemoveConstMeta,
      argValues: [path, fields],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiRemoveConstMeta => const TaskConstMeta(
        debugName: "remove",
        argNames: ["path", "fields"],
      );

  @override
  Future<Uint8List> crateApiApiRemoveFromBytes(
      {required List<int> bytes, required List<TagField> fields}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_list_tag_field(fields, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiRemoveFromBytesConstMeta,
      argValues: [bytes, fields],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiRemoveFromBytesConstMeta => const TaskConstMeta(
        debugName: "remove_from_bytes",
        argNames: ["bytes", "fields"],
      );

  @override
  Future<TagChanges> crateApiTagChangesTagChangesDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tag_changes,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTagChangesTagChangesDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagChangesTagChangesDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "tag_changes_default",
        argNames: [],
      );

  @override
  Future<bool> crateApiTagChangesTagChangesIsEmpty({required TagChanges that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_tag_changes(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTagChangesTagChangesIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagChangesTagChangesIsEmptyConstMeta =>
      const TaskConstMeta(
        debugName: "tag_changes_is_empty",
        argNames: ["that"],
      );

  @override
  Future<Tag> crateApiTagTagDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tag,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTagTagDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagTagDefaultConstMeta => const TaskConstMeta(
        debugName: "tag_default",
        argNames: [],
      );

  @override
  Future<bool> crateApiTagTagIsEmpty({required Tag that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_tag(that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiTagTagIsEmptyConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagTagIsEmptyConstMeta => const TaskConstMeta(
        debugName: "tag_is_empty",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiTagChangesUpdate(
      {required String path, required TagChanges changes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_tag_changes(changes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiTagChangesUpdateConstMeta,
      argValues: [path, changes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagChangesUpdateConstMeta => const TaskConstMeta(
        debugName: "update",
        argNames: ["path", "changes"],
      );

  @override
  Future<Uint8List> crateApiTagChangesUpdateFromBytes(
      {required List<int> bytes, required TagChanges changes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_box_autoadd_tag_changes(changes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiTagChangesUpdateFromBytesConstMeta,
      argValues: [bytes, changes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTagChangesUpdateFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "update_from_bytes",
        argNames: ["bytes", "changes"],
      );

  @override
  Future<void> crateApiApiWrite({required String path, required Tag data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_tag(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiWriteConstMeta,
      argValues: [path, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiWriteConstMeta => const TaskConstMeta(
        debugName: "write",
        argNames: ["path", "data"],
      );

  @override
  Future<Uint8List> crateApiApiWriteToBytes(
      {required List<int> bytes, required Tag data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_box_autoadd_tag(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_haudiotagger_error,
      ),
      constMeta: kCrateApiApiWriteToBytesConstMeta,
      argValues: [bytes, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiApiWriteToBytesConstMeta => const TaskConstMeta(
        debugName: "write_to_bytes",
        argNames: ["bytes", "data"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioProperties dco_decode_audio_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return AudioProperties(
      durationMicros: dco_decode_opt_box_autoadd_i_64(arr[0]),
      bitrate: dco_decode_opt_box_autoadd_u_32(arr[1]),
      sampleRate: dco_decode_opt_box_autoadd_u_32(arr[2]),
      channels: dco_decode_opt_box_autoadd_u_32(arr[3]),
      bitsPerSample: dco_decode_opt_box_autoadd_u_32(arr[4]),
      codec: dco_decode_String(arr[5]),
      containerFormat: dco_decode_String(arr[6]),
      lossless: dco_decode_bool(arr[7]),
      bitrateMode: dco_decode_bitrate_mode(arr[8]),
      fileSize: dco_decode_opt_box_autoadd_u_64(arr[9]),
    );
  }

  @protected
  BitrateMode dco_decode_bitrate_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BitrateMode.values[raw as int];
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  MimeType dco_decode_box_autoadd_mime_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_mime_type(raw);
  }

  @protected
  Tag dco_decode_box_autoadd_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tag(raw);
  }

  @protected
  TagChanges dco_decode_box_autoadd_tag_changes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_tag_changes(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HaudiotaggerError dco_decode_haudiotagger_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return HaudiotaggerError_InvalidPath();
      case 1:
        return HaudiotaggerError_NoTags();
      case 2:
        return HaudiotaggerError_OpenFile(
          message: dco_decode_String(raw[1]),
        );
      case 3:
        return HaudiotaggerError_Write(
          message: dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<Picture> dco_decode_list_picture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_picture).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TagField> dco_decode_list_tag_field(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tag_field).toList();
  }

  @protected
  MimeType dco_decode_mime_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MimeType.values[raw as int];
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_32(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  MimeType? dco_decode_opt_box_autoadd_mime_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_mime_type(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  List<Picture>? dco_decode_opt_list_picture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_picture(raw);
  }

  @protected
  Picture dco_decode_picture(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return Picture(
      pictureType: dco_decode_picture_type(arr[0]),
      mimeType: dco_decode_opt_box_autoadd_mime_type(arr[1]),
      bytes: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  PictureType dco_decode_picture_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PictureType.values[raw as int];
  }

  @protected
  Tag dco_decode_tag(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return Tag(
      title: dco_decode_opt_String(arr[0]),
      trackArtist: dco_decode_opt_String(arr[1]),
      album: dco_decode_opt_String(arr[2]),
      albumArtist: dco_decode_opt_String(arr[3]),
      year: dco_decode_opt_box_autoadd_u_32(arr[4]),
      genre: dco_decode_opt_String(arr[5]),
      trackNumber: dco_decode_opt_box_autoadd_u_32(arr[6]),
      trackTotal: dco_decode_opt_box_autoadd_u_32(arr[7]),
      discNumber: dco_decode_opt_box_autoadd_u_32(arr[8]),
      discTotal: dco_decode_opt_box_autoadd_u_32(arr[9]),
      lyrics: dco_decode_opt_String(arr[10]),
      comment: dco_decode_opt_String(arr[11]),
      duration: dco_decode_opt_box_autoadd_u_32(arr[12]),
      pictures: dco_decode_list_picture(arr[13]),
      bpm: dco_decode_opt_box_autoadd_f_32(arr[14]),
    );
  }

  @protected
  TagChanges dco_decode_tag_changes(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return TagChanges(
      title: dco_decode_opt_String(arr[0]),
      trackArtist: dco_decode_opt_String(arr[1]),
      album: dco_decode_opt_String(arr[2]),
      albumArtist: dco_decode_opt_String(arr[3]),
      year: dco_decode_opt_box_autoadd_u_32(arr[4]),
      genre: dco_decode_opt_String(arr[5]),
      trackNumber: dco_decode_opt_box_autoadd_u_32(arr[6]),
      trackTotal: dco_decode_opt_box_autoadd_u_32(arr[7]),
      discNumber: dco_decode_opt_box_autoadd_u_32(arr[8]),
      discTotal: dco_decode_opt_box_autoadd_u_32(arr[9]),
      lyrics: dco_decode_opt_String(arr[10]),
      comment: dco_decode_opt_String(arr[11]),
      pictures: dco_decode_opt_list_picture(arr[12]),
      bpm: dco_decode_opt_box_autoadd_f_32(arr[13]),
    );
  }

  @protected
  TagField dco_decode_tag_field(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TagField.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioProperties sse_decode_audio_properties(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_durationMicros = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_bitrate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_sampleRate = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_channels = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_bitsPerSample = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_codec = sse_decode_String(deserializer);
    var var_containerFormat = sse_decode_String(deserializer);
    var var_lossless = sse_decode_bool(deserializer);
    var var_bitrateMode = sse_decode_bitrate_mode(deserializer);
    var var_fileSize = sse_decode_opt_box_autoadd_u_64(deserializer);
    return AudioProperties(
        durationMicros: var_durationMicros,
        bitrate: var_bitrate,
        sampleRate: var_sampleRate,
        channels: var_channels,
        bitsPerSample: var_bitsPerSample,
        codec: var_codec,
        containerFormat: var_containerFormat,
        lossless: var_lossless,
        bitrateMode: var_bitrateMode,
        fileSize: var_fileSize);
  }

  @protected
  BitrateMode sse_decode_bitrate_mode(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BitrateMode.values[inner];
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_32(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  MimeType sse_decode_box_autoadd_mime_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_mime_type(deserializer));
  }

  @protected
  Tag sse_decode_box_autoadd_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tag(deserializer));
  }

  @protected
  TagChanges sse_decode_box_autoadd_tag_changes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_tag_changes(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  HaudiotaggerError sse_decode_haudiotagger_error(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return HaudiotaggerError_InvalidPath();
      case 1:
        return HaudiotaggerError_NoTags();
      case 2:
        var var_message = sse_decode_String(deserializer);
        return HaudiotaggerError_OpenFile(message: var_message);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return HaudiotaggerError_Write(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<Picture> sse_decode_list_picture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Picture>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_picture(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TagField> sse_decode_list_tag_field(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TagField>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tag_field(deserializer));
    }
    return ans_;
  }

  @protected
  MimeType sse_decode_mime_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MimeType.values[inner];
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  MimeType? sse_decode_opt_box_autoadd_mime_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_mime_type(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<Picture>? sse_decode_opt_list_picture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_picture(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Picture sse_decode_picture(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pictureType = sse_decode_picture_type(deserializer);
    var var_mimeType = sse_decode_opt_box_autoadd_mime_type(deserializer);
    var var_bytes = sse_decode_list_prim_u_8_strict(deserializer);
    return Picture(
        pictureType: var_pictureType, mimeType: var_mimeType, bytes: var_bytes);
  }

  @protected
  PictureType sse_decode_picture_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PictureType.values[inner];
  }

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_trackArtist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_albumArtist = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_trackNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_trackTotal = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discTotal = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lyrics = sse_decode_opt_String(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    var var_duration = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_pictures = sse_decode_list_picture(deserializer);
    var var_bpm = sse_decode_opt_box_autoadd_f_32(deserializer);
    return Tag(
        title: var_title,
        trackArtist: var_trackArtist,
        album: var_album,
        albumArtist: var_albumArtist,
        year: var_year,
        genre: var_genre,
        trackNumber: var_trackNumber,
        trackTotal: var_trackTotal,
        discNumber: var_discNumber,
        discTotal: var_discTotal,
        lyrics: var_lyrics,
        comment: var_comment,
        duration: var_duration,
        pictures: var_pictures,
        bpm: var_bpm);
  }

  @protected
  TagChanges sse_decode_tag_changes(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_title = sse_decode_opt_String(deserializer);
    var var_trackArtist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_albumArtist = sse_decode_opt_String(deserializer);
    var var_year = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_genre = sse_decode_opt_String(deserializer);
    var var_trackNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_trackTotal = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discNumber = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_discTotal = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_lyrics = sse_decode_opt_String(deserializer);
    var var_comment = sse_decode_opt_String(deserializer);
    var var_pictures = sse_decode_opt_list_picture(deserializer);
    var var_bpm = sse_decode_opt_box_autoadd_f_32(deserializer);
    return TagChanges(
        title: var_title,
        trackArtist: var_trackArtist,
        album: var_album,
        albumArtist: var_albumArtist,
        year: var_year,
        genre: var_genre,
        trackNumber: var_trackNumber,
        trackTotal: var_trackTotal,
        discNumber: var_discNumber,
        discTotal: var_discTotal,
        lyrics: var_lyrics,
        comment: var_comment,
        pictures: var_pictures,
        bpm: var_bpm);
  }

  @protected
  TagField sse_decode_tag_field(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TagField.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_properties(
      AudioProperties self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_i_64(self.durationMicros, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitrate, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sampleRate, serializer);
    sse_encode_opt_box_autoadd_u_32(self.channels, serializer);
    sse_encode_opt_box_autoadd_u_32(self.bitsPerSample, serializer);
    sse_encode_String(self.codec, serializer);
    sse_encode_String(self.containerFormat, serializer);
    sse_encode_bool(self.lossless, serializer);
    sse_encode_bitrate_mode(self.bitrateMode, serializer);
    sse_encode_opt_box_autoadd_u_64(self.fileSize, serializer);
  }

  @protected
  void sse_encode_bitrate_mode(BitrateMode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_mime_type(
      MimeType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_mime_type(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tag(Tag self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tag(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_tag_changes(
      TagChanges self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_tag_changes(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_haudiotagger_error(
      HaudiotaggerError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case HaudiotaggerError_InvalidPath():
        sse_encode_i_32(0, serializer);
      case HaudiotaggerError_NoTags():
        sse_encode_i_32(1, serializer);
      case HaudiotaggerError_OpenFile(message: final message):
        sse_encode_i_32(2, serializer);
        sse_encode_String(message, serializer);
      case HaudiotaggerError_Write(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_picture(List<Picture> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_picture(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_tag_field(
      List<TagField> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tag_field(item, serializer);
    }
  }

  @protected
  void sse_encode_mime_type(MimeType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_mime_type(
      MimeType? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_mime_type(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_picture(
      List<Picture>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_picture(self, serializer);
    }
  }

  @protected
  void sse_encode_picture(Picture self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_picture_type(self.pictureType, serializer);
    sse_encode_opt_box_autoadd_mime_type(self.mimeType, serializer);
    sse_encode_list_prim_u_8_strict(self.bytes, serializer);
  }

  @protected
  void sse_encode_picture_type(PictureType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.trackArtist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.albumArtist, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackNumber, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackTotal, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discNumber, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discTotal, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
    sse_encode_opt_String(self.comment, serializer);
    sse_encode_opt_box_autoadd_u_32(self.duration, serializer);
    sse_encode_list_picture(self.pictures, serializer);
    sse_encode_opt_box_autoadd_f_32(self.bpm, serializer);
  }

  @protected
  void sse_encode_tag_changes(TagChanges self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.trackArtist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_String(self.albumArtist, serializer);
    sse_encode_opt_box_autoadd_u_32(self.year, serializer);
    sse_encode_opt_String(self.genre, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackNumber, serializer);
    sse_encode_opt_box_autoadd_u_32(self.trackTotal, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discNumber, serializer);
    sse_encode_opt_box_autoadd_u_32(self.discTotal, serializer);
    sse_encode_opt_String(self.lyrics, serializer);
    sse_encode_opt_String(self.comment, serializer);
    sse_encode_opt_list_picture(self.pictures, serializer);
    sse_encode_opt_box_autoadd_f_32(self.bpm, serializer);
  }

  @protected
  void sse_encode_tag_field(TagField self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
