// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/api.dart';
import 'api/audio_properties.dart';
import 'api/error.dart';
import 'api/normalization.dart';
import 'api/picture.dart';
import 'api/pipeline.dart';
import 'api/tag.dart';
import 'api/tag_changes.dart';
import 'api/tag_field.dart';
import 'api/validation.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioFileInfo dco_decode_audio_file_info(dynamic raw);

  @protected
  AudioProperties dco_decode_audio_properties(dynamic raw);

  @protected
  BatchBytesResult dco_decode_batch_bytes_result(dynamic raw);

  @protected
  BatchResult dco_decode_batch_result(dynamic raw);

  @protected
  BitrateMode dco_decode_bitrate_mode(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  Id3v2Version dco_decode_box_autoadd_id_3_v_2_version(dynamic raw);

  @protected
  MimeType dco_decode_box_autoadd_mime_type(dynamic raw);

  @protected
  NormalizeOptions dco_decode_box_autoadd_normalize_options(dynamic raw);

  @protected
  Tag dco_decode_box_autoadd_tag(dynamic raw);

  @protected
  TagChanges dco_decode_box_autoadd_tag_changes(dynamic raw);

  @protected
  TagPipeline dco_decode_box_autoadd_tag_pipeline(dynamic raw);

  @protected
  TransformRule dco_decode_box_autoadd_transform_rule(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ValidationResult dco_decode_box_autoadd_validation_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  HaudiotaggerError dco_decode_haudiotagger_error(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  Id3v2Version dco_decode_id_3_v_2_version(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Picture> dco_decode_list_picture(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<(int, String)> dco_decode_list_record_u_32_string(dynamic raw);

  @protected
  List<TagField> dco_decode_list_tag_field(dynamic raw);

  @protected
  List<TransformRule> dco_decode_list_transform_rule(dynamic raw);

  @protected
  List<ValidationIssue> dco_decode_list_validation_issue(dynamic raw);

  @protected
  MimeType dco_decode_mime_type(dynamic raw);

  @protected
  NormalizeOptions dco_decode_normalize_options(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  Id3v2Version? dco_decode_opt_box_autoadd_id_3_v_2_version(dynamic raw);

  @protected
  MimeType? dco_decode_opt_box_autoadd_mime_type(dynamic raw);

  @protected
  Tag? dco_decode_opt_box_autoadd_tag(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  List<Picture>? dco_decode_opt_list_picture(dynamic raw);

  @protected
  Picture dco_decode_picture(dynamic raw);

  @protected
  PictureType dco_decode_picture_type(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (int, String) dco_decode_record_u_32_string(dynamic raw);

  @protected
  Tag dco_decode_tag(dynamic raw);

  @protected
  TagChanges dco_decode_tag_changes(dynamic raw);

  @protected
  TagField dco_decode_tag_field(dynamic raw);

  @protected
  TagPipeline dco_decode_tag_pipeline(dynamic raw);

  @protected
  TransformRule dco_decode_transform_rule(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  ValidationIssue dco_decode_validation_issue(dynamic raw);

  @protected
  ValidationResult dco_decode_validation_result(dynamic raw);

  @protected
  ValidationSeverity dco_decode_validation_severity(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioFileInfo sse_decode_audio_file_info(SseDeserializer deserializer);

  @protected
  AudioProperties sse_decode_audio_properties(SseDeserializer deserializer);

  @protected
  BatchBytesResult sse_decode_batch_bytes_result(SseDeserializer deserializer);

  @protected
  BatchResult sse_decode_batch_result(SseDeserializer deserializer);

  @protected
  BitrateMode sse_decode_bitrate_mode(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Id3v2Version sse_decode_box_autoadd_id_3_v_2_version(
      SseDeserializer deserializer);

  @protected
  MimeType sse_decode_box_autoadd_mime_type(SseDeserializer deserializer);

  @protected
  NormalizeOptions sse_decode_box_autoadd_normalize_options(
      SseDeserializer deserializer);

  @protected
  Tag sse_decode_box_autoadd_tag(SseDeserializer deserializer);

  @protected
  TagChanges sse_decode_box_autoadd_tag_changes(SseDeserializer deserializer);

  @protected
  TagPipeline sse_decode_box_autoadd_tag_pipeline(SseDeserializer deserializer);

  @protected
  TransformRule sse_decode_box_autoadd_transform_rule(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ValidationResult sse_decode_box_autoadd_validation_result(
      SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  HaudiotaggerError sse_decode_haudiotagger_error(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  Id3v2Version sse_decode_id_3_v_2_version(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
      SseDeserializer deserializer);

  @protected
  List<Picture> sse_decode_list_picture(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<(int, String)> sse_decode_list_record_u_32_string(
      SseDeserializer deserializer);

  @protected
  List<TagField> sse_decode_list_tag_field(SseDeserializer deserializer);

  @protected
  List<TransformRule> sse_decode_list_transform_rule(
      SseDeserializer deserializer);

  @protected
  List<ValidationIssue> sse_decode_list_validation_issue(
      SseDeserializer deserializer);

  @protected
  MimeType sse_decode_mime_type(SseDeserializer deserializer);

  @protected
  NormalizeOptions sse_decode_normalize_options(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  Id3v2Version? sse_decode_opt_box_autoadd_id_3_v_2_version(
      SseDeserializer deserializer);

  @protected
  MimeType? sse_decode_opt_box_autoadd_mime_type(SseDeserializer deserializer);

  @protected
  Tag? sse_decode_opt_box_autoadd_tag(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  List<Picture>? sse_decode_opt_list_picture(SseDeserializer deserializer);

  @protected
  Picture sse_decode_picture(SseDeserializer deserializer);

  @protected
  PictureType sse_decode_picture_type(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  (int, String) sse_decode_record_u_32_string(SseDeserializer deserializer);

  @protected
  Tag sse_decode_tag(SseDeserializer deserializer);

  @protected
  TagChanges sse_decode_tag_changes(SseDeserializer deserializer);

  @protected
  TagField sse_decode_tag_field(SseDeserializer deserializer);

  @protected
  TagPipeline sse_decode_tag_pipeline(SseDeserializer deserializer);

  @protected
  TransformRule sse_decode_transform_rule(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  ValidationIssue sse_decode_validation_issue(SseDeserializer deserializer);

  @protected
  ValidationResult sse_decode_validation_result(SseDeserializer deserializer);

  @protected
  ValidationSeverity sse_decode_validation_severity(
      SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_file_info(AudioFileInfo self, SseSerializer serializer);

  @protected
  void sse_encode_audio_properties(
      AudioProperties self, SseSerializer serializer);

  @protected
  void sse_encode_batch_bytes_result(
      BatchBytesResult self, SseSerializer serializer);

  @protected
  void sse_encode_batch_result(BatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_bitrate_mode(BitrateMode self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
      PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_id_3_v_2_version(
      Id3v2Version self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_mime_type(
      MimeType self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_normalize_options(
      NormalizeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tag_changes(
      TagChanges self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tag_pipeline(
      TagPipeline self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_transform_rule(
      TransformRule self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_validation_result(
      ValidationResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_haudiotagger_error(
      HaudiotaggerError self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_id_3_v_2_version(Id3v2Version self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_prim_u_8_strict(
      List<Uint8List> self, SseSerializer serializer);

  @protected
  void sse_encode_list_picture(List<Picture> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_u_32_string(
      List<(int, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tag_field(List<TagField> self, SseSerializer serializer);

  @protected
  void sse_encode_list_transform_rule(
      List<TransformRule> self, SseSerializer serializer);

  @protected
  void sse_encode_list_validation_issue(
      List<ValidationIssue> self, SseSerializer serializer);

  @protected
  void sse_encode_mime_type(MimeType self, SseSerializer serializer);

  @protected
  void sse_encode_normalize_options(
      NormalizeOptions self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
      PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_id_3_v_2_version(
      Id3v2Version? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_mime_type(
      MimeType? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_tag(Tag? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_picture(
      List<Picture>? self, SseSerializer serializer);

  @protected
  void sse_encode_picture(Picture self, SseSerializer serializer);

  @protected
  void sse_encode_picture_type(PictureType self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_record_u_32_string(
      (int, String) self, SseSerializer serializer);

  @protected
  void sse_encode_tag(Tag self, SseSerializer serializer);

  @protected
  void sse_encode_tag_changes(TagChanges self, SseSerializer serializer);

  @protected
  void sse_encode_tag_field(TagField self, SseSerializer serializer);

  @protected
  void sse_encode_tag_pipeline(TagPipeline self, SseSerializer serializer);

  @protected
  void sse_encode_transform_rule(TransformRule self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_validation_issue(
      ValidationIssue self, SseSerializer serializer);

  @protected
  void sse_encode_validation_result(
      ValidationResult self, SseSerializer serializer);

  @protected
  void sse_encode_validation_severity(
      ValidationSeverity self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
