// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/error.dart';
import 'api/picture.dart';
import 'api/tag.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detect_from_bytes`, `evict`, `get`, `insert`, `new`, `read_from_url_native`, `select_strategy`, `tag_from_lofty_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RangeCache`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Read audio metadata from a remote URL.
///
/// Downloads the file (or relevant portions via HTTP range requests) and
/// parses the metadata tag. Supports MP3, FLAC, OGG, Opus, MP4, WAV, AIFF,
/// APE, and WavPack.
///
/// Use [UrlReadStrategy] to control how the file is fetched:
/// - `Auto` (default): picks the best strategy based on file size and format.
/// - `Full`: downloads the entire file before parsing.
/// - `Progressive`: fetches only the header + tag progressively.
/// - `RandomAccess`: uses HTTP range-backed seekable reader.
///
/// On WASM, all strategies fall back to Full download (Progressive and
/// RandomAccess are not yet implemented for async range fetching).
Future<Tag> readFromUrl(
        {required String url, required UrlReadStrategy strategy}) =>
    RustLib.instance.api.crateRemoteReadFromUrl(url: url, strategy: strategy);

enum DetectedFormat {
  mp3,
  flac,
  ogg,
  opus,
  mp4,
  wav,
  aiff,
  ape,
  wavPack,
  unknown,
  ;
}

class HttpResponse {
  final int status;
  final Uint8List body;

  const HttpResponse({
    required this.status,
    required this.body,
  });

  @override
  int get hashCode => status.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          body == other.body;
}

class RemoteFileInfo {
  final BigInt? size;
  final bool acceptRanges;
  final String? contentType;

  const RemoteFileInfo({
    this.size,
    required this.acceptRanges,
    this.contentType,
  });

  @override
  int get hashCode =>
      size.hashCode ^ acceptRanges.hashCode ^ contentType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteFileInfo &&
          runtimeType == other.runtimeType &&
          size == other.size &&
          acceptRanges == other.acceptRanges &&
          contentType == other.contentType;
}

enum UrlReadStrategy {
  auto,
  full,
  progressive,
  randomAccess,
  ;

  static Future<UrlReadStrategy> default_() =>
      RustLib.instance.api.crateRemoteUrlReadStrategyDefault();
}
