name: haudiotagger
description: Read and write audio metadata in Flutter. Supports MP3, FLAC, OGG, MP4, WAV, AIFF, and more. Powered by Rust for fast, reliable performance.
version: 1.1.0
homepage: https://github.com/Hirdaya-Shrestha/haudiotagger
repository: https://github.com/Hirdaya-Shrestha/haudiotagger

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  ffi: ^2.2.0
  flutter_rust_bridge: ^2.13.0
  freezed_annotation: ^3.1.0
  rust_lib_haudiotagger:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^21.0.0
  build_runner: ^2.4.6
  freezed: ^4.0.0
  analyzer: ^13.3.0

resolution: workspace

flutter:
  plugin:
    platforms:
      android:
        package: com.ha.nep.haudiotagger
        pluginClass: HaudiotaggerPlugin
      ios:
        pluginClass: HaudiotaggerPlugin
      linux:
        pluginClass: HaudiotaggerPlugin
      macos:
        pluginClass: HaudiotaggerPlugin
      windows:
        pluginClass: HaudiotaggerPluginCApi
      web:
        pluginClass: HaudiotaggerWeb
        fileName: haudiotagger_web.dart
  assets:
    - web/wasm/haudiotagger_bg.wasm
    - web/wasm/haudiotagger.js
