// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'audio_properties.dart';
import 'error.dart';
import 'normalization.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';
import 'pipeline.dart';
import 'tag.dart';
import 'tag_changes.dart';
import 'tag_field.dart';
import 'validation.dart';

// These functions are ignored because they are not marked as `pub`: `apply_tag_to_lofty_tag`, `build_file_info`, `clear_field`, `collect_batch_bytes_result`, `collect_batch_result`, `convert_id3v2_impl`, `extract_custom_tags_from_file`, `extract_custom_tags_from_lofty_tag`, `extract_id3v2_version`, `extract_tag_formats`, `file_format_name`, `format_tag_type`, `get_file_from_bytes`, `get_file`, `is_mp3`, `is_standard_vorbis_key`, `prebuild_tag_bytes`, `remove_custom_tag_impl`, `remove_id3v1_impl`, `set_custom_tag_impl`, `strip_ape`, `strip_id3v1`, `strip_id3v2`, `tag_from_file`, `write_lofty_tag_to_mp3_bytes`, `write_mp3_bytes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

Future<Tag> read({required String path}) =>
    RustLib.instance.api.crateApiApiRead(path: path);

/// Read metadata from in-memory bytes (for web/WASM).
Future<Tag> readFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiReadFromBytes(bytes: bytes);

Future<void> write({required String path, required Tag data}) =>
    RustLib.instance.api.crateApiApiWrite(path: path, data: data);

/// Write metadata to in-memory bytes, returns modified bytes (for web/WASM).
Future<Uint8List> writeToBytes({required List<int> bytes, required Tag data}) =>
    RustLib.instance.api.crateApiApiWriteToBytes(bytes: bytes, data: data);

/// Remove the given `fields` from the tag at `path`, keeping everything else.
Future<void> remove({required String path, required List<TagField> fields}) =>
    RustLib.instance.api.crateApiApiRemove(path: path, fields: fields);

/// Remove the given `fields` from a tag held in `bytes`, returning the modified bytes.
Future<Uint8List> removeFromBytes(
        {required List<int> bytes, required List<TagField> fields}) =>
    RustLib.instance.api
        .crateApiApiRemoveFromBytes(bytes: bytes, fields: fields);

/// Remove all metadata from the file at `path`.
Future<void> clear({required String path}) =>
    RustLib.instance.api.crateApiApiClear(path: path);

/// Remove all metadata from a tag held in `bytes`, returning the modified bytes.
Future<Uint8List> clearFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiClearFromBytes(bytes: bytes);

/// Write the same tag to multiple files. Returns the number of successes and failures.
Future<BatchResult> batchWrite(
        {required List<String> paths, required Tag data}) =>
    RustLib.instance.api.crateApiApiBatchWrite(paths: paths, data: data);

/// Apply the same [TagChanges] to multiple files. Returns the number of successes and failures.
Future<BatchResult> batchUpdateChanges(
        {required List<String> paths, required TagChanges changes}) =>
    RustLib.instance.api
        .crateApiApiBatchUpdateChanges(paths: paths, changes: changes);

/// Write the same tag to multiple in-memory byte arrays. Returns modified bytes.
///
/// Optimized path: builds the lofty tag and serializes it **once**, then
/// reuses the pre-serialized bytes for every file. This eliminates redundant
/// tag construction and serialization across the batch.
Future<BatchBytesResult> batchWriteFromBytes(
        {required List<Uint8List> byteArrays, required Tag data}) =>
    RustLib.instance.api
        .crateApiApiBatchWriteFromBytes(byteArrays: byteArrays, data: data);

/// Apply the same [TagChanges] to multiple in-memory byte arrays. Returns modified bytes.
Future<BatchBytesResult> batchUpdateChangesFromBytes(
        {required List<Uint8List> byteArrays, required TagChanges changes}) =>
    RustLib.instance.api.crateApiApiBatchUpdateChangesFromBytes(
        byteArrays: byteArrays, changes: changes);

/// Returns the list of tag formats present in the file at `path`.
/// Possible values: "ID3v1", "ID3v2", "APE", "iTunes", "VorbisComments", "RiffInfo", "AiffText".
Future<List<String>> getTagFormats({required String path}) =>
    RustLib.instance.api.crateApiApiGetTagFormats(path: path);

/// Returns the list of tag formats present in the in-memory `bytes`.
/// Possible values: "ID3v1", "ID3v2", "APE", "iTunes", "VorbisComments", "RiffInfo", "AiffText".
Future<List<String>> getTagFormatsFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiGetTagFormatsFromBytes(bytes: bytes);

/// Get all custom tags from the file at `path`.
/// Returns a map of key -> value for format-specific custom tags.
/// For ID3v2: TXXX frames (user-defined text).
/// For Vorbis Comments: non-standard keys.
/// For APE: non-standard keys.
Future<Map<String, String>> getCustomTags({required String path}) =>
    RustLib.instance.api.crateApiApiGetCustomTags(path: path);

/// Get all custom tags from in-memory `bytes`.
Future<Map<String, String>> getCustomTagsFromBytes(
        {required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiGetCustomTagsFromBytes(bytes: bytes);

/// Set a custom tag on the file at `path`.
/// For ID3v2: creates a TXXX frame with the key as description.
/// For Vorbis Comments: inserts with the key directly.
/// For APE: inserts with the key directly.
Future<void> setCustomTag(
        {required String path, required String key, required String value}) =>
    RustLib.instance.api
        .crateApiApiSetCustomTag(path: path, key: key, value: value);

/// Set a custom tag on in-memory `bytes`, returning the modified bytes.
Future<Uint8List> setCustomTagFromBytes(
        {required List<int> bytes,
        required String key,
        required String value}) =>
    RustLib.instance.api
        .crateApiApiSetCustomTagFromBytes(bytes: bytes, key: key, value: value);

/// Remove a custom tag from the file at `path`.
Future<void> removeCustomTag({required String path, required String key}) =>
    RustLib.instance.api.crateApiApiRemoveCustomTag(path: path, key: key);

/// Remove a custom tag from in-memory `bytes`, returning the modified bytes.
Future<Uint8List> removeCustomTagFromBytes(
        {required List<int> bytes, required String key}) =>
    RustLib.instance.api
        .crateApiApiRemoveCustomTagFromBytes(bytes: bytes, key: key);

/// Get the ID3v2 version of the tag in the file at `path`.
/// Returns None if the file has no ID3v2 tag.
Future<Id3v2Version?> getId3V2Version({required String path}) =>
    RustLib.instance.api.crateApiApiGetId3V2Version(path: path);

/// Get the ID3v2 version of the tag in in-memory `bytes`.
/// Returns None if the bytes have no ID3v2 tag.
Future<Id3v2Version?> getId3V2VersionFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiGetId3V2VersionFromBytes(bytes: bytes);

/// Convert the ID3v2 tag in the file at `path` to the specified version.
/// ID3v2.2 is not supported for writing (lofty doesn't support it).
/// ID3v2.3 uses `WriteOptions::use_id3v23(true)`.
/// ID3v2.4 uses default `WriteOptions`.
Future<void> convertId3V2(
        {required String path, required Id3v2Version version}) =>
    RustLib.instance.api.crateApiApiConvertId3V2(path: path, version: version);

/// Convert the ID3v2 tag in in-memory `bytes` to the specified version, returning modified bytes.
Future<Uint8List> convertId3V2FromBytes(
        {required List<int> bytes, required Id3v2Version version}) =>
    RustLib.instance.api
        .crateApiApiConvertId3V2FromBytes(bytes: bytes, version: version);

/// Remove the ID3v1 tag from the file at `path`.
Future<void> removeId3V1({required String path}) =>
    RustLib.instance.api.crateApiApiRemoveId3V1(path: path);

/// Remove the ID3v1 tag from in-memory `bytes`, returning the modified bytes.
Future<Uint8List> removeId3V1FromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiRemoveId3V1FromBytes(bytes: bytes);

/// Inspect an audio file, returning all available information in one call.
Future<AudioFileInfo> inspect({required String path}) =>
    RustLib.instance.api.crateApiApiInspect(path: path);

/// Inspect audio data from in-memory bytes.
Future<AudioFileInfo> inspectFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiInspectFromBytes(bytes: bytes);

/// Validate the tag at `path` and return any issues found.
Future<ValidationResult> validate({required String path}) =>
    RustLib.instance.api.crateApiApiValidate(path: path);

/// Validate in-memory `bytes` and return any issues found.
Future<ValidationResult> validateFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiValidateFromBytes(bytes: bytes);

/// Validate a Tag directly (for use after manual edits).
Future<ValidationResult> validateTag({required Tag tag}) =>
    RustLib.instance.api.crateApiApiValidateTag(tag: tag);

/// Normalize the tag at [path] using default options, returning the cleaned tag.
/// Does NOT write to disk — use [write] to persist the result.
Future<Tag> normalize({required String path}) =>
    RustLib.instance.api.crateApiApiNormalize(path: path);

/// Normalize in-memory bytes using default options, returning the cleaned bytes.
Future<Uint8List> normalizeBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiNormalizeBytes(bytes: bytes);

/// Normalize a Tag directly with custom options.
Future<Tag> normalizeTag(
        {required Tag tag, required NormalizeOptions options}) =>
    RustLib.instance.api.crateApiApiNormalizeTag(tag: tag, options: options);

/// Format a filename from a tag using a pattern string.
///
/// Supported placeholders:
/// `{title}`, `{artist}`, `{album}`, `{albumArtist}`, `{track}`,
/// `{trackTotal}`, `{disc}`, `{discTotal}`, `{year}`, `{genre}`
///
/// Example: `format_filename(tag, "{track}. {title}")` → `"01. My Song"`
Future<String> formatFilename({required Tag tag, required String pattern}) =>
    RustLib.instance.api.crateApiApiFormatFilename(tag: tag, pattern: pattern);

/// Rename a file based on its metadata using a pattern.
///
/// Returns the new file path on success.
Future<String> renameFile({required String path, required String pattern}) =>
    RustLib.instance.api.crateApiApiRenameFile(path: path, pattern: pattern);

/// Apply a pipeline of transformation rules to a tag.
Future<Tag> applyPipeline(
        {required Tag tag, required List<TransformRule> rules}) =>
    RustLib.instance.api.crateApiApiApplyPipeline(tag: tag, rules: rules);

/// Apply a pipeline of rules to multiple files. Returns successes and failures.
Future<BatchResult> batchTransform(
        {required List<String> paths, required List<TransformRule> rules}) =>
    RustLib.instance.api.crateApiApiBatchTransform(paths: paths, rules: rules);

/// Copy metadata from source to destination file in a single FFI call.
Future<void> copyMetadata(
        {required String source,
        required String destination,
        required bool includeArtwork,
        required bool includeLyrics,
        required bool includeCustomTags}) =>
    RustLib.instance.api.crateApiApiCopyMetadata(
        source: source,
        destination: destination,
        includeArtwork: includeArtwork,
        includeLyrics: includeLyrics,
        includeCustomTags: includeCustomTags);

/// Copy metadata from source bytes to destination bytes in a single FFI call.
Future<Uint8List> copyMetadataFromBytes(
        {required List<int> sourceBytes,
        required List<int> destinationBytes,
        required bool includeArtwork,
        required bool includeLyrics,
        required bool includeCustomTags}) =>
    RustLib.instance.api.crateApiApiCopyMetadataFromBytes(
        sourceBytes: sourceBytes,
        destinationBytes: destinationBytes,
        includeArtwork: includeArtwork,
        includeLyrics: includeLyrics,
        includeCustomTags: includeCustomTags);

/// Apply a pipeline to a file and write the result in a single FFI call.
Future<void> processFile(
        {required String path, required List<TransformRule> rules}) =>
    RustLib.instance.api.crateApiApiProcessFile(path: path, rules: rules);

/// Apply a pipeline to byte data and return modified bytes in a single FFI call.
Future<Uint8List> processBytes(
        {required List<int> bytes, required List<TransformRule> rules}) =>
    RustLib.instance.api.crateApiApiProcessBytes(bytes: bytes, rules: rules);

/// Apply a pipeline to multiple files. Returns successes and failures.
Future<BatchResult> processBatch(
        {required List<String> paths, required List<TransformRule> rules}) =>
    RustLib.instance.api.crateApiApiProcessBatch(paths: paths, rules: rules);

/// Apply a pipeline to multiple byte arrays. Returns modified bytes.
Future<BatchBytesResult> processBatchBytes(
        {required List<Uint8List> byteArrays,
        required List<TransformRule> rules}) =>
    RustLib.instance.api
        .crateApiApiProcessBatchBytes(byteArrays: byteArrays, rules: rules);

/// Comprehensive info about an audio file, returned by `inspect`.
class AudioFileInfo {
  /// The audio format (e.g. `MP3`, `FLAC`).
  final String format;

  /// The tag format (e.g. `ID3v2`, `VorbisComments`).
  final String tagFormat;

  /// Technical audio properties.
  final AudioProperties properties;

  /// The metadata tag, if present.
  final Tag? metadata;

  /// Embedded pictures, if any.
  final List<Picture> pictures;

  /// File size in bytes.
  final BigInt size;

  const AudioFileInfo({
    required this.format,
    required this.tagFormat,
    required this.properties,
    this.metadata,
    required this.pictures,
    required this.size,
  });

  @override
  int get hashCode =>
      format.hashCode ^
      tagFormat.hashCode ^
      properties.hashCode ^
      metadata.hashCode ^
      pictures.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFileInfo &&
          runtimeType == other.runtimeType &&
          format == other.format &&
          tagFormat == other.tagFormat &&
          properties == other.properties &&
          metadata == other.metadata &&
          pictures == other.pictures &&
          size == other.size;
}

/// Result of a batch operation on in-memory bytes.
class BatchBytesResult {
  /// Successfully processed byte arrays, in the same order as input.
  final List<Uint8List> results;

  /// Number of files that failed.
  final int failures;

  /// Indices that failed (0-based), paired with error messages.
  final List<(int, String)> errors;

  const BatchBytesResult({
    required this.results,
    required this.failures,
    required this.errors,
  });

  @override
  int get hashCode => results.hashCode ^ failures.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchBytesResult &&
          runtimeType == other.runtimeType &&
          results == other.results &&
          failures == other.failures &&
          errors == other.errors;
}

/// Result of a batch operation on file paths.
class BatchResult {
  /// Number of files successfully processed.
  final int successes;

  /// Number of files that failed.
  final int failures;

  /// Paths that failed, paired with error messages.
  final List<(String, String)> errors;

  const BatchResult({
    required this.successes,
    required this.failures,
    required this.errors,
  });

  @override
  int get hashCode => successes.hashCode ^ failures.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BatchResult &&
          runtimeType == other.runtimeType &&
          successes == other.successes &&
          failures == other.failures &&
          errors == other.errors;
}

/// Represents the ID3v2 version to use when writing.
enum Id3v2Version {
  /// ID3v2.2 (3-character frame IDs, limited features)
  v2,

  /// ID3v2.3 (widely supported, recommended for compatibility)
  v3,

  /// ID3v2.4 (latest spec, but less software support)
  v4,
  ;
}
