// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';
import 'tag.dart';
import 'tag_field.dart';

// These functions are ignored because they are not marked as `pub`: `apply_tag_to_lofty_tag`, `clear_field`, `format_tag_type`, `get_file_from_bytes`, `get_file`, `is_mp3`, `strip_ape`, `strip_id3v1`, `strip_id3v2`, `tag_from_file`, `write_mp3_bytes`

Future<Tag> read({required String path}) =>
    RustLib.instance.api.crateApiApiRead(path: path);

/// Read metadata from in-memory bytes (for web/WASM).
Future<Tag> readFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiReadFromBytes(bytes: bytes);

Future<void> write({required String path, required Tag data}) =>
    RustLib.instance.api.crateApiApiWrite(path: path, data: data);

/// Write metadata to in-memory bytes, returns modified bytes (for web/WASM).
Future<Uint8List> writeToBytes({required List<int> bytes, required Tag data}) =>
    RustLib.instance.api.crateApiApiWriteToBytes(bytes: bytes, data: data);

/// Remove the given `fields` from the tag at `path`, keeping everything else.
Future<void> remove({required String path, required List<TagField> fields}) =>
    RustLib.instance.api.crateApiApiRemove(path: path, fields: fields);

/// Remove the given `fields` from a tag held in `bytes`, returning the modified bytes.
Future<Uint8List> removeFromBytes(
        {required List<int> bytes, required List<TagField> fields}) =>
    RustLib.instance.api
        .crateApiApiRemoveFromBytes(bytes: bytes, fields: fields);

/// Remove all metadata from the file at `path`.
Future<void> clear({required String path}) =>
    RustLib.instance.api.crateApiApiClear(path: path);

/// Remove all metadata from a tag held in `bytes`, returning the modified bytes.
Future<Uint8List> clearFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiClearFromBytes(bytes: bytes);

/// Returns the list of tag formats present in the file at `path`.
/// Possible values: "ID3v1", "ID3v2", "APE", "iTunes", "VorbisComments", "RiffInfo", "AiffText".
Future<List<String>> getTagFormats({required String path}) =>
    RustLib.instance.api.crateApiApiGetTagFormats(path: path);

/// Returns the list of tag formats present in the in-memory `bytes`.
/// Possible values: "ID3v1", "ID3v2", "APE", "iTunes", "VorbisComments", "RiffInfo", "AiffText".
Future<List<String>> getTagFormatsFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiApiGetTagFormatsFromBytes(bytes: bytes);
