// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_file`, `type_info`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Read the technical audio properties of the file at `path`.
Future<AudioProperties> readProperties({required String path}) =>
    RustLib.instance.api.crateApiAudioPropertiesReadProperties(path: path);

/// Read the technical audio properties from in-memory bytes (for web/WASM).
Future<AudioProperties> readPropertiesFromBytes({required List<int> bytes}) =>
    RustLib.instance.api
        .crateApiAudioPropertiesReadPropertiesFromBytes(bytes: bytes);

/// Immutable, read-only technical audio properties of a file.
class AudioProperties {
  /// Duration of the audio, in microseconds.
  final PlatformInt64? durationMicros;

  /// Overall bitrate (kbps).
  final int? bitrate;

  /// Sample rate (Hz).
  final int? sampleRate;

  /// Number of channels.
  final int? channels;

  /// Bits per sample.
  final int? bitsPerSample;

  /// The audio codec (ex. `MP3`, `FLAC`, `AAC`).
  final String codec;

  /// The container format (ex. `MP3`, `MP4`, `Ogg`).
  final String containerFormat;

  /// Whether the audio is lossless.
  final bool lossless;

  /// Bitrate encoding mode, when known.
  final BitrateMode bitrateMode;

  /// File size in bytes.
  final BigInt? fileSize;

  const AudioProperties({
    this.durationMicros,
    this.bitrate,
    this.sampleRate,
    this.channels,
    this.bitsPerSample,
    required this.codec,
    required this.containerFormat,
    required this.lossless,
    required this.bitrateMode,
    this.fileSize,
  });

  @override
  int get hashCode =>
      durationMicros.hashCode ^
      bitrate.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      bitsPerSample.hashCode ^
      codec.hashCode ^
      containerFormat.hashCode ^
      lossless.hashCode ^
      bitrateMode.hashCode ^
      fileSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioProperties &&
          runtimeType == other.runtimeType &&
          durationMicros == other.durationMicros &&
          bitrate == other.bitrate &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitsPerSample == other.bitsPerSample &&
          codec == other.codec &&
          containerFormat == other.containerFormat &&
          lossless == other.lossless &&
          bitrateMode == other.bitrateMode &&
          fileSize == other.fileSize;
}

/// Bitrate encoding mode, when known.
enum BitrateMode {
  /// Could not be determined.
  unknown,

  /// Constant bitrate.
  cbr,

  /// Variable bitrate.
  vbr,
  ;
}
