// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_id3v2_header`, `decode_syncsafe`, `encode_syncsafe`, `parse_chap_frame`, `serialize_chap_frames`, `strip_chapter_frames`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Read ID3v2 CHAP frames from MP3 bytes.
Future<List<Chapter>> readChaptersFromMp3Bytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiChaptersReadChaptersFromMp3Bytes(bytes: bytes);

/// Write chapters as ID3v2 CHAP frames to MP3 bytes.
/// Strips existing CHAP/CTOC frames, then appends new ones.
Future<Uint8List> writeChaptersToMp3Bytes(
        {required List<int> bytes, required List<Chapter> chapters}) =>
    RustLib.instance.api.crateApiChaptersWriteChaptersToMp3Bytes(
        bytes: bytes, chapters: chapters);

/// Read chapters from in-memory bytes (for web/WASM).
Future<List<Chapter>> readChaptersFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiChaptersReadChaptersFromBytes(bytes: bytes);

/// Write chapters to in-memory bytes, returning modified bytes.
Future<Uint8List> writeChaptersToBytes(
        {required List<int> bytes, required List<Chapter> chapters}) =>
    RustLib.instance.api
        .crateApiChaptersWriteChaptersToBytes(bytes: bytes, chapters: chapters);

/// Read chapters from the file at `path`.
Future<List<Chapter>> getChapters({required String path}) =>
    RustLib.instance.api.crateApiChaptersGetChapters(path: path);

/// Write chapters to the file at `path`.
Future<void> setChapters(
        {required String path, required List<Chapter> chapters}) =>
    RustLib.instance.api
        .crateApiChaptersSetChapters(path: path, chapters: chapters);

/// Represents a chapter marker in an audio file.
class Chapter {
  /// Chapter title.
  final String title;

  /// Start time in milliseconds.
  final BigInt startMs;

  /// End time in milliseconds.
  final BigInt endMs;

  const Chapter({
    required this.title,
    required this.startMs,
    required this.endMs,
  });

  @override
  int get hashCode => title.hashCode ^ startMs.hashCode ^ endMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Chapter &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          startMs == other.startMs &&
          endMs == other.endMs;
}
