// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

@freezed
sealed class HaudiotaggerError
    with _$HaudiotaggerError
    implements FrbException {
  const HaudiotaggerError._();

  const factory HaudiotaggerError.invalidPath() = HaudiotaggerError_InvalidPath;
  const factory HaudiotaggerError.noTags() = HaudiotaggerError_NoTags;
  const factory HaudiotaggerError.openFile({
    required String message,
  }) = HaudiotaggerError_OpenFile;
  const factory HaudiotaggerError.write({
    required String message,
  }) = HaudiotaggerError_Write;
}
