// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_to_lofty_tag`, `from_lofty_tag`, `get_str`, `merge`, `read_extended_or_empty`, `set_str`, `write_extended_to_bytes_inner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// Read extended metadata from a file path.
Future<ExtendedTag> readExtended({required String path}) =>
    RustLib.instance.api.crateApiExtendedReadExtended(path: path);

/// Read extended metadata from in-memory bytes.
Future<ExtendedTag> readExtendedFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiExtendedReadExtendedFromBytes(bytes: bytes);

/// Write extended metadata to a file, replacing the existing extended fields.
Future<void> writeExtended({required String path, required ExtendedTag data}) =>
    RustLib.instance.api.crateApiExtendedWriteExtended(path: path, data: data);

/// Write extended metadata to bytes, returning the modified bytes.
Future<Uint8List> writeExtendedToBytes(
        {required List<int> bytes, required ExtendedTag data}) =>
    RustLib.instance.api
        .crateApiExtendedWriteExtendedToBytes(bytes: bytes, data: data);

/// Apply partial changes to the extended tag at `path`.
Future<void> updateExtended(
        {required String path, required ExtendedChanges changes}) =>
    RustLib.instance.api
        .crateApiExtendedUpdateExtended(path: path, changes: changes);

/// Apply partial changes to extended tag bytes, returning modified bytes.
Future<Uint8List> updateExtendedFromBytes(
        {required List<int> bytes, required ExtendedChanges changes}) =>
    RustLib.instance.api.crateApiExtendedUpdateExtendedFromBytes(
        bytes: bytes, changes: changes);

/// Remove all extended fields from the file, preserving standard fields.
Future<void> removeExtended({required String path}) =>
    RustLib.instance.api.crateApiExtendedRemoveExtended(path: path);

/// Remove all extended fields from bytes, returning modified bytes.
Future<Uint8List> removeExtendedFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiExtendedRemoveExtendedFromBytes(bytes: bytes);

/// A partial set of extended tag fields for partial updates.
class ExtendedChanges {
  final String? musicBrainzRecordingId;
  final String? musicBrainzTrackId;
  final String? musicBrainzReleaseId;
  final String? musicBrainzReleaseGroupId;
  final String? musicBrainzArtistId;
  final String? musicBrainzReleaseArtistId;
  final String? musicBrainzWorkId;
  final String? musicBrainzReleaseType;
  final String? acoustId;
  final String? acoustIdFingerprint;
  final String? isrc;
  final String? barcode;
  final String? catalogNumber;
  final String? arranger;
  final String? conductor;
  final String? director;
  final String? engineer;
  final String? lyricist;
  final String? mixDj;
  final String? mixEngineer;
  final String? performer;
  final String? producer;
  final String? publisher;
  final String? label;
  final String? remixer;
  final String? writer;
  final String? composer;
  final String? originalLyricist;
  final String? recordingDate;
  final String? releaseDate;
  final String? originalReleaseDate;
  final String? initialKey;
  final String? color;
  final String? mood;
  final String? audioFileUrl;
  final String? audioSourceUrl;
  final String? commercialInformationUrl;
  final String? copyrightUrl;
  final String? trackArtistUrl;
  final String? radioStationUrl;
  final String? paymentUrl;
  final String? publisherUrl;
  final String? copyrightMessage;
  final String? license;
  final String? podcastDescription;
  final String? podcastSeriesCategory;
  final String? podcastUrl;
  final String? podcastGlobalUniqueId;
  final String? podcastKeywords;
  final String? setSubtitle;
  final String? showName;
  final String? contentGroup;
  final String? trackSubtitle;
  final String? language;
  final String? script;
  final String? parentalAdvisory;
  final String? fileOwner;
  final String? originalFileName;
  final String? originalMediaType;
  final String? encodedBy;
  final String? encoderSoftware;
  final String? encoderSettings;

  const ExtendedChanges({
    this.musicBrainzRecordingId,
    this.musicBrainzTrackId,
    this.musicBrainzReleaseId,
    this.musicBrainzReleaseGroupId,
    this.musicBrainzArtistId,
    this.musicBrainzReleaseArtistId,
    this.musicBrainzWorkId,
    this.musicBrainzReleaseType,
    this.acoustId,
    this.acoustIdFingerprint,
    this.isrc,
    this.barcode,
    this.catalogNumber,
    this.arranger,
    this.conductor,
    this.director,
    this.engineer,
    this.lyricist,
    this.mixDj,
    this.mixEngineer,
    this.performer,
    this.producer,
    this.publisher,
    this.label,
    this.remixer,
    this.writer,
    this.composer,
    this.originalLyricist,
    this.recordingDate,
    this.releaseDate,
    this.originalReleaseDate,
    this.initialKey,
    this.color,
    this.mood,
    this.audioFileUrl,
    this.audioSourceUrl,
    this.commercialInformationUrl,
    this.copyrightUrl,
    this.trackArtistUrl,
    this.radioStationUrl,
    this.paymentUrl,
    this.publisherUrl,
    this.copyrightMessage,
    this.license,
    this.podcastDescription,
    this.podcastSeriesCategory,
    this.podcastUrl,
    this.podcastGlobalUniqueId,
    this.podcastKeywords,
    this.setSubtitle,
    this.showName,
    this.contentGroup,
    this.trackSubtitle,
    this.language,
    this.script,
    this.parentalAdvisory,
    this.fileOwner,
    this.originalFileName,
    this.originalMediaType,
    this.encodedBy,
    this.encoderSoftware,
    this.encoderSettings,
  });

  static Future<ExtendedChanges> default_() =>
      RustLib.instance.api.crateApiExtendedExtendedChangesDefault();

  Future<bool> isEmpty() =>
      RustLib.instance.api.crateApiExtendedExtendedChangesIsEmpty(
        that: this,
      );

  @override
  int get hashCode =>
      musicBrainzRecordingId.hashCode ^
      musicBrainzTrackId.hashCode ^
      musicBrainzReleaseId.hashCode ^
      musicBrainzReleaseGroupId.hashCode ^
      musicBrainzArtistId.hashCode ^
      musicBrainzReleaseArtistId.hashCode ^
      musicBrainzWorkId.hashCode ^
      musicBrainzReleaseType.hashCode ^
      acoustId.hashCode ^
      acoustIdFingerprint.hashCode ^
      isrc.hashCode ^
      barcode.hashCode ^
      catalogNumber.hashCode ^
      arranger.hashCode ^
      conductor.hashCode ^
      director.hashCode ^
      engineer.hashCode ^
      lyricist.hashCode ^
      mixDj.hashCode ^
      mixEngineer.hashCode ^
      performer.hashCode ^
      producer.hashCode ^
      publisher.hashCode ^
      label.hashCode ^
      remixer.hashCode ^
      writer.hashCode ^
      composer.hashCode ^
      originalLyricist.hashCode ^
      recordingDate.hashCode ^
      releaseDate.hashCode ^
      originalReleaseDate.hashCode ^
      initialKey.hashCode ^
      color.hashCode ^
      mood.hashCode ^
      audioFileUrl.hashCode ^
      audioSourceUrl.hashCode ^
      commercialInformationUrl.hashCode ^
      copyrightUrl.hashCode ^
      trackArtistUrl.hashCode ^
      radioStationUrl.hashCode ^
      paymentUrl.hashCode ^
      publisherUrl.hashCode ^
      copyrightMessage.hashCode ^
      license.hashCode ^
      podcastDescription.hashCode ^
      podcastSeriesCategory.hashCode ^
      podcastUrl.hashCode ^
      podcastGlobalUniqueId.hashCode ^
      podcastKeywords.hashCode ^
      setSubtitle.hashCode ^
      showName.hashCode ^
      contentGroup.hashCode ^
      trackSubtitle.hashCode ^
      language.hashCode ^
      script.hashCode ^
      parentalAdvisory.hashCode ^
      fileOwner.hashCode ^
      originalFileName.hashCode ^
      originalMediaType.hashCode ^
      encodedBy.hashCode ^
      encoderSoftware.hashCode ^
      encoderSettings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtendedChanges &&
          runtimeType == other.runtimeType &&
          musicBrainzRecordingId == other.musicBrainzRecordingId &&
          musicBrainzTrackId == other.musicBrainzTrackId &&
          musicBrainzReleaseId == other.musicBrainzReleaseId &&
          musicBrainzReleaseGroupId == other.musicBrainzReleaseGroupId &&
          musicBrainzArtistId == other.musicBrainzArtistId &&
          musicBrainzReleaseArtistId == other.musicBrainzReleaseArtistId &&
          musicBrainzWorkId == other.musicBrainzWorkId &&
          musicBrainzReleaseType == other.musicBrainzReleaseType &&
          acoustId == other.acoustId &&
          acoustIdFingerprint == other.acoustIdFingerprint &&
          isrc == other.isrc &&
          barcode == other.barcode &&
          catalogNumber == other.catalogNumber &&
          arranger == other.arranger &&
          conductor == other.conductor &&
          director == other.director &&
          engineer == other.engineer &&
          lyricist == other.lyricist &&
          mixDj == other.mixDj &&
          mixEngineer == other.mixEngineer &&
          performer == other.performer &&
          producer == other.producer &&
          publisher == other.publisher &&
          label == other.label &&
          remixer == other.remixer &&
          writer == other.writer &&
          composer == other.composer &&
          originalLyricist == other.originalLyricist &&
          recordingDate == other.recordingDate &&
          releaseDate == other.releaseDate &&
          originalReleaseDate == other.originalReleaseDate &&
          initialKey == other.initialKey &&
          color == other.color &&
          mood == other.mood &&
          audioFileUrl == other.audioFileUrl &&
          audioSourceUrl == other.audioSourceUrl &&
          commercialInformationUrl == other.commercialInformationUrl &&
          copyrightUrl == other.copyrightUrl &&
          trackArtistUrl == other.trackArtistUrl &&
          radioStationUrl == other.radioStationUrl &&
          paymentUrl == other.paymentUrl &&
          publisherUrl == other.publisherUrl &&
          copyrightMessage == other.copyrightMessage &&
          license == other.license &&
          podcastDescription == other.podcastDescription &&
          podcastSeriesCategory == other.podcastSeriesCategory &&
          podcastUrl == other.podcastUrl &&
          podcastGlobalUniqueId == other.podcastGlobalUniqueId &&
          podcastKeywords == other.podcastKeywords &&
          setSubtitle == other.setSubtitle &&
          showName == other.showName &&
          contentGroup == other.contentGroup &&
          trackSubtitle == other.trackSubtitle &&
          language == other.language &&
          script == other.script &&
          parentalAdvisory == other.parentalAdvisory &&
          fileOwner == other.fileOwner &&
          originalFileName == other.originalFileName &&
          originalMediaType == other.originalMediaType &&
          encodedBy == other.encodedBy &&
          encoderSoftware == other.encoderSoftware &&
          encoderSettings == other.encoderSettings;
}

/// Extended metadata fields not covered by the basic `Tag`.
///
/// These fields are commonly used by music libraries (MusicBrainz, AcoustID),
/// professional audio tools, and metadata providers. They are kept separate
/// from the core `Tag` to maintain a clean separation between the metadata
/// engine and metadata providers.
class ExtendedTag {
  final String? musicBrainzRecordingId;
  final String? musicBrainzTrackId;
  final String? musicBrainzReleaseId;
  final String? musicBrainzReleaseGroupId;
  final String? musicBrainzArtistId;
  final String? musicBrainzReleaseArtistId;
  final String? musicBrainzWorkId;
  final String? musicBrainzReleaseType;
  final String? acoustId;
  final String? acoustIdFingerprint;
  final String? isrc;
  final String? barcode;
  final String? catalogNumber;
  final String? arranger;
  final String? conductor;
  final String? director;
  final String? engineer;
  final String? lyricist;
  final String? mixDj;
  final String? mixEngineer;
  final String? performer;
  final String? producer;
  final String? publisher;
  final String? label;
  final String? remixer;
  final String? writer;
  final String? composer;
  final String? originalLyricist;
  final String? recordingDate;
  final String? releaseDate;
  final String? originalReleaseDate;
  final String? initialKey;
  final String? color;
  final String? mood;
  final String? audioFileUrl;
  final String? audioSourceUrl;
  final String? commercialInformationUrl;
  final String? copyrightUrl;
  final String? trackArtistUrl;
  final String? radioStationUrl;
  final String? paymentUrl;
  final String? publisherUrl;
  final String? copyrightMessage;
  final String? license;
  final String? podcastDescription;
  final String? podcastSeriesCategory;
  final String? podcastUrl;
  final String? podcastGlobalUniqueId;
  final String? podcastKeywords;
  final String? setSubtitle;
  final String? showName;
  final String? contentGroup;
  final String? trackSubtitle;
  final String? language;
  final String? script;
  final String? parentalAdvisory;
  final String? fileOwner;
  final String? originalFileName;
  final String? originalMediaType;
  final String? encodedBy;
  final String? encoderSoftware;
  final String? encoderSettings;

  const ExtendedTag({
    this.musicBrainzRecordingId,
    this.musicBrainzTrackId,
    this.musicBrainzReleaseId,
    this.musicBrainzReleaseGroupId,
    this.musicBrainzArtistId,
    this.musicBrainzReleaseArtistId,
    this.musicBrainzWorkId,
    this.musicBrainzReleaseType,
    this.acoustId,
    this.acoustIdFingerprint,
    this.isrc,
    this.barcode,
    this.catalogNumber,
    this.arranger,
    this.conductor,
    this.director,
    this.engineer,
    this.lyricist,
    this.mixDj,
    this.mixEngineer,
    this.performer,
    this.producer,
    this.publisher,
    this.label,
    this.remixer,
    this.writer,
    this.composer,
    this.originalLyricist,
    this.recordingDate,
    this.releaseDate,
    this.originalReleaseDate,
    this.initialKey,
    this.color,
    this.mood,
    this.audioFileUrl,
    this.audioSourceUrl,
    this.commercialInformationUrl,
    this.copyrightUrl,
    this.trackArtistUrl,
    this.radioStationUrl,
    this.paymentUrl,
    this.publisherUrl,
    this.copyrightMessage,
    this.license,
    this.podcastDescription,
    this.podcastSeriesCategory,
    this.podcastUrl,
    this.podcastGlobalUniqueId,
    this.podcastKeywords,
    this.setSubtitle,
    this.showName,
    this.contentGroup,
    this.trackSubtitle,
    this.language,
    this.script,
    this.parentalAdvisory,
    this.fileOwner,
    this.originalFileName,
    this.originalMediaType,
    this.encodedBy,
    this.encoderSoftware,
    this.encoderSettings,
  });

  static Future<ExtendedTag> default_() =>
      RustLib.instance.api.crateApiExtendedExtendedTagDefault();

  Future<bool> isEmpty() =>
      RustLib.instance.api.crateApiExtendedExtendedTagIsEmpty(
        that: this,
      );

  @override
  int get hashCode =>
      musicBrainzRecordingId.hashCode ^
      musicBrainzTrackId.hashCode ^
      musicBrainzReleaseId.hashCode ^
      musicBrainzReleaseGroupId.hashCode ^
      musicBrainzArtistId.hashCode ^
      musicBrainzReleaseArtistId.hashCode ^
      musicBrainzWorkId.hashCode ^
      musicBrainzReleaseType.hashCode ^
      acoustId.hashCode ^
      acoustIdFingerprint.hashCode ^
      isrc.hashCode ^
      barcode.hashCode ^
      catalogNumber.hashCode ^
      arranger.hashCode ^
      conductor.hashCode ^
      director.hashCode ^
      engineer.hashCode ^
      lyricist.hashCode ^
      mixDj.hashCode ^
      mixEngineer.hashCode ^
      performer.hashCode ^
      producer.hashCode ^
      publisher.hashCode ^
      label.hashCode ^
      remixer.hashCode ^
      writer.hashCode ^
      composer.hashCode ^
      originalLyricist.hashCode ^
      recordingDate.hashCode ^
      releaseDate.hashCode ^
      originalReleaseDate.hashCode ^
      initialKey.hashCode ^
      color.hashCode ^
      mood.hashCode ^
      audioFileUrl.hashCode ^
      audioSourceUrl.hashCode ^
      commercialInformationUrl.hashCode ^
      copyrightUrl.hashCode ^
      trackArtistUrl.hashCode ^
      radioStationUrl.hashCode ^
      paymentUrl.hashCode ^
      publisherUrl.hashCode ^
      copyrightMessage.hashCode ^
      license.hashCode ^
      podcastDescription.hashCode ^
      podcastSeriesCategory.hashCode ^
      podcastUrl.hashCode ^
      podcastGlobalUniqueId.hashCode ^
      podcastKeywords.hashCode ^
      setSubtitle.hashCode ^
      showName.hashCode ^
      contentGroup.hashCode ^
      trackSubtitle.hashCode ^
      language.hashCode ^
      script.hashCode ^
      parentalAdvisory.hashCode ^
      fileOwner.hashCode ^
      originalFileName.hashCode ^
      originalMediaType.hashCode ^
      encodedBy.hashCode ^
      encoderSoftware.hashCode ^
      encoderSettings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtendedTag &&
          runtimeType == other.runtimeType &&
          musicBrainzRecordingId == other.musicBrainzRecordingId &&
          musicBrainzTrackId == other.musicBrainzTrackId &&
          musicBrainzReleaseId == other.musicBrainzReleaseId &&
          musicBrainzReleaseGroupId == other.musicBrainzReleaseGroupId &&
          musicBrainzArtistId == other.musicBrainzArtistId &&
          musicBrainzReleaseArtistId == other.musicBrainzReleaseArtistId &&
          musicBrainzWorkId == other.musicBrainzWorkId &&
          musicBrainzReleaseType == other.musicBrainzReleaseType &&
          acoustId == other.acoustId &&
          acoustIdFingerprint == other.acoustIdFingerprint &&
          isrc == other.isrc &&
          barcode == other.barcode &&
          catalogNumber == other.catalogNumber &&
          arranger == other.arranger &&
          conductor == other.conductor &&
          director == other.director &&
          engineer == other.engineer &&
          lyricist == other.lyricist &&
          mixDj == other.mixDj &&
          mixEngineer == other.mixEngineer &&
          performer == other.performer &&
          producer == other.producer &&
          publisher == other.publisher &&
          label == other.label &&
          remixer == other.remixer &&
          writer == other.writer &&
          composer == other.composer &&
          originalLyricist == other.originalLyricist &&
          recordingDate == other.recordingDate &&
          releaseDate == other.releaseDate &&
          originalReleaseDate == other.originalReleaseDate &&
          initialKey == other.initialKey &&
          color == other.color &&
          mood == other.mood &&
          audioFileUrl == other.audioFileUrl &&
          audioSourceUrl == other.audioSourceUrl &&
          commercialInformationUrl == other.commercialInformationUrl &&
          copyrightUrl == other.copyrightUrl &&
          trackArtistUrl == other.trackArtistUrl &&
          radioStationUrl == other.radioStationUrl &&
          paymentUrl == other.paymentUrl &&
          publisherUrl == other.publisherUrl &&
          copyrightMessage == other.copyrightMessage &&
          license == other.license &&
          podcastDescription == other.podcastDescription &&
          podcastSeriesCategory == other.podcastSeriesCategory &&
          podcastUrl == other.podcastUrl &&
          podcastGlobalUniqueId == other.podcastGlobalUniqueId &&
          podcastKeywords == other.podcastKeywords &&
          setSubtitle == other.setSubtitle &&
          showName == other.showName &&
          contentGroup == other.contentGroup &&
          trackSubtitle == other.trackSubtitle &&
          language == other.language &&
          script == other.script &&
          parentalAdvisory == other.parentalAdvisory &&
          fileOwner == other.fileOwner &&
          originalFileName == other.originalFileName &&
          originalMediaType == other.originalMediaType &&
          encodedBy == other.encodedBy &&
          encoderSoftware == other.encoderSoftware &&
          encoderSettings == other.encoderSettings;
}
