// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';
import 'tag.dart';

// These functions are ignored because they are not marked as `pub`: `apply_normalize`, `normalize_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<Tag> normalize({required Tag tag, required NormalizeOptions opts}) =>
    RustLib.instance.api.crateApiNormalizationNormalize(tag: tag, opts: opts);

class NormalizeOptions {
  /// Trim leading/trailing whitespace from all string fields.
  final bool trimValues;

  /// Collapse multiple whitespace characters into a single space.
  final bool normalizeWhitespace;

  /// Apply Unicode NFKC normalization (full compatibility decomposition + canonical composition).
  final bool normalizeUnicode;

  /// Remove fields that are empty strings after normalization.
  final bool removeEmptyValues;

  const NormalizeOptions({
    required this.trimValues,
    required this.normalizeWhitespace,
    required this.normalizeUnicode,
    required this.removeEmptyValues,
  });

  static Future<NormalizeOptions> default_() =>
      RustLib.instance.api.crateApiNormalizationNormalizeOptionsDefault();

  @override
  int get hashCode =>
      trimValues.hashCode ^
      normalizeWhitespace.hashCode ^
      normalizeUnicode.hashCode ^
      removeEmptyValues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NormalizeOptions &&
          runtimeType == other.runtimeType &&
          trimValues == other.trimValues &&
          normalizeWhitespace == other.normalizeWhitespace &&
          normalizeUnicode == other.normalizeUnicode &&
          removeEmptyValues == other.removeEmptyValues;
}
