// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';
import 'tag.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Read audio metadata from a remote URL.
///
/// Downloads the file (or relevant portions via HTTP range requests) and
/// parses the metadata tag. Supports MP3, FLAC, OGG, Opus, MP4, WAV, AIFF,
/// APE, and WavPack.
///
/// Use [UrlReadStrategy] to control how the file is fetched:
/// - `Auto` (default): picks the best strategy based on file size and format.
/// - `Full`: downloads the entire file before parsing.
/// - `Progressive`: fetches only the header + tag progressively.
/// - `RandomAccess`: uses HTTP range-backed seekable reader.
///
/// On WASM, all strategies fall back to Full download (Progressive and
/// RandomAccess are not yet implemented for async range fetching).
Future<Tag> readFromUrl(
        {required String url, required UrlReadStrategy strategy}) =>
    RustLib.instance.api
        .crateApiRemoteReadReadFromUrl(url: url, strategy: strategy);

enum UrlReadStrategy {
  auto,
  full,
  progressive,
  randomAccess,
  ;

  static Future<UrlReadStrategy> default_() =>
      RustLib.instance.api.crateApiRemoteReadUrlReadStrategyDefault();
}
