// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';
import 'tag.dart';

// These functions are ignored because they are not marked as `pub`: `detect_from_bytes`, `detect_from_url`, `evict`, `get_all`, `get_range`, `get`, `head`, `insert`, `new`, `new`, `new`, `read_at`, `retry`, `select_strategy`, `tag_from_lofty_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DetectedFormat`, `HttpResponse`, `RangeCache`, `RemoteFileInfo`, `RemoteReader`, `ReqwestHttpClient`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `read`, `seek`

/// Read audio metadata from a remote URL.
///
/// Downloads the file (or relevant portions via HTTP range requests) and
/// parses the metadata tag. Supports MP3, FLAC, OGG, Opus, MP4, WAV, AIFF,
/// APE, and WavPack.
///
/// Use [UrlReadStrategy] to control how the file is fetched:
/// - `Auto` (default): picks the best strategy based on file size and format.
/// - `Full`: downloads the entire file before parsing.
/// - `Progressive`: fetches only the header + tag progressively.
/// - `RandomAccess`: uses HTTP range-backed seekable reader.
Future<Tag> readFromUrl(
        {required String url, required UrlReadStrategy strategy}) =>
    RustLib.instance.api
        .crateApiRemoteReadReadFromUrl(url: url, strategy: strategy);

enum UrlReadStrategy {
  auto,
  full,
  progressive,
  randomAccess,
  ;

  static Future<UrlReadStrategy> default_() =>
      RustLib.instance.api.crateApiRemoteReadUrlReadStrategyDefault();
}
