// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// A specific tag field that can be individually removed.
enum TagField {
  /// The title of the song.
  title,

  /// The artist of the song.
  artist,

  /// The album the song is from.
  album,

  /// The artist of the album.
  albumArtist,

  /// The year the song was made.
  year,

  /// The genre of the song.
  genre,

  /// The position of the song in a list.
  trackNumber,

  /// The total amount of songs in a list.
  trackTotal,

  /// The position of the disc in a list.
  discNumber,

  /// The total amount of discs in a list.
  discTotal,

  /// The lyrics of the song.
  lyrics,

  /// A comment about the song.
  comment,

  /// Beats per minute.
  bpm,

  /// All embedded pictures.
  pictures,
  ;
}
