// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';

// These functions are ignored because they are not marked as `pub`: `merge`, `read_bytes_or_empty`, `read_or_empty`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Apply [changes] to the tag at `path`, preserving any fields not mentioned.
void update({required String path, required TagChanges changes}) =>
    RustLib.instance.api.crateApiTagChangesUpdate(path: path, changes: changes);

/// Apply [changes] to a tag held in `bytes`, returning the modified bytes.
Uint8List updateFromBytes(
        {required List<int> bytes, required TagChanges changes}) =>
    RustLib.instance.api
        .crateApiTagChangesUpdateFromBytes(bytes: bytes, changes: changes);

/// A partial set of tag fields to apply on top of an existing tag.
///
/// Every field is optional. When applying via `update`, a `Some` value replaces
/// the corresponding field on the existing tag, while `None` leaves it untouched.
class TagChanges {
  final String? title;
  final String? trackArtist;
  final String? album;
  final String? albumArtist;
  final int? year;
  final String? genre;
  final int? trackNumber;
  final int? trackTotal;
  final int? discNumber;
  final int? discTotal;
  final String? lyrics;
  final String? comment;
  final List<Picture>? pictures;
  final double? bpm;

  const TagChanges({
    this.title,
    this.trackArtist,
    this.album,
    this.albumArtist,
    this.year,
    this.genre,
    this.trackNumber,
    this.trackTotal,
    this.discNumber,
    this.discTotal,
    this.lyrics,
    this.comment,
    this.pictures,
    this.bpm,
  });

  static TagChanges default_() =>
      RustLib.instance.api.crateApiTagChangesTagChangesDefault();

  /// Returns `true` if no fields are set.
  bool isEmpty() => RustLib.instance.api.crateApiTagChangesTagChangesIsEmpty(
        that: this,
      );

  @override
  int get hashCode =>
      title.hashCode ^
      trackArtist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      year.hashCode ^
      genre.hashCode ^
      trackNumber.hashCode ^
      trackTotal.hashCode ^
      discNumber.hashCode ^
      discTotal.hashCode ^
      lyrics.hashCode ^
      comment.hashCode ^
      pictures.hashCode ^
      bpm.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TagChanges &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          trackArtist == other.trackArtist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          year == other.year &&
          genre == other.genre &&
          trackNumber == other.trackNumber &&
          trackTotal == other.trackTotal &&
          discNumber == other.discNumber &&
          discTotal == other.discTotal &&
          lyrics == other.lyrics &&
          comment == other.comment &&
          pictures == other.pictures &&
          bpm == other.bpm;
}
