// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'picture.dart';
import 'tag.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

Future<ValidationResult> validate({required Tag tag}) =>
    RustLib.instance.api.crateApiValidationValidate(tag: tag);

class ValidationIssue {
  final String field;
  final String message;
  final ValidationSeverity severity;

  const ValidationIssue({
    required this.field,
    required this.message,
    required this.severity,
  });

  @override
  int get hashCode => field.hashCode ^ message.hashCode ^ severity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidationIssue &&
          runtimeType == other.runtimeType &&
          field == other.field &&
          message == other.message &&
          severity == other.severity;
}

class ValidationResult {
  final List<ValidationIssue> issues;

  const ValidationResult({
    required this.issues,
  });

  Future<bool> isValid() =>
      RustLib.instance.api.crateApiValidationValidationResultIsValid(
        that: this,
      );

  @override
  int get hashCode => issues.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ValidationResult &&
          runtimeType == other.runtimeType &&
          issues == other.issues;
}

enum ValidationSeverity {
  error,
  warning,
  ;
}
