name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - uses: dtolnay/rust-toolchain@stable

      - name: Install MUSL dependencies
        run: sudo apt-get update && sudo apt-get install -y musl-tools lcov

      - name: Install dependencies
        run: flutter pub get
        working-directory: haudiotagger
      - run: cd cli && flutter pub get

      - name: Build native library
        run: dart run cli build linux -v

      - name: Run tests with coverage
        working-directory: haudiotagger
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/haudiotagger/linux
        run: |
          flutter test --coverage
          lcov --ignore-errors unused --remove coverage/lcov.info '**/frb_generated*' '**/src/rust/*' -o coverage/lcov_filtered.info
          mv coverage/lcov_filtered.info coverage/lcov.info

      - name: Update coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.COVERAGE_GIST_ID }}
          LCOV_FILE: haudiotagger/coverage/lcov.info
        run: bash .github/scripts/report_coverage.sh
