name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish_to_release:
    name: Publish Artifacts to Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}

      - name: Get CI run SHA
        id: ci
        run: |
          SHA=$(git rev-parse HEAD)
          echo "sha=$SHA" >> "$GITHUB_OUTPUT"

      - name: Download CI build artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: ci.yml
          commit: ${{ steps.ci.outputs.sha }}
          if_no_artifact_found: warn
          path: ci-artifacts

      - name: Prepare release files
        run: |
          # Linux
          tar -C ci-artifacts/linux -czvf linux.tar.gz .
          # Android
          tar -C ci-artifacts/android -czvf android.tar.gz .
          # Windows
          tar -C ci-artifacts/windows -czvf windows.tar.gz .
          # macOS
          zip -j macos.zip ci-artifacts/macos/*
          # iOS
          cd ci-artifacts/ios && zip -r ../../ios.zip . && cd ../..
          # Web
          zip -j web.zip ci-artifacts/web/haudiotagger_bg.wasm ci-artifacts/web/haudiotagger.js

      - name: Add to Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            linux.tar.gz
            android.tar.gz
            windows.tar.gz
            macos.zip
            ios.zip
            web.zip
