name: Publish

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build_and_upload:
    name: Build and Upload Artifacts
    strategy:
      matrix:
        include:
          - target: linux
            os: ubuntu-22.04
            path: haudiotagger/linux/libhaudiotagger.so
          - target: android
            os: ubuntu-latest
            path: |
              haudiotagger/android/src/main/jniLibs/arm64-v8a/libhaudiotagger.so
              haudiotagger/android/src/main/jniLibs/armeabi-v7a/libhaudiotagger.so
              haudiotagger/android/src/main/jniLibs/x86_64/libhaudiotagger.so
              haudiotagger/android/src/main/jniLibs/x86/libhaudiotagger.so
          - target: windows
            os: windows-latest
            path: haudiotagger/windows/haudiotagger.dll
          - target: macos
            os: macos-latest
            path: haudiotagger/macos/Frameworks/haudiotagger.xcframework
          - target: ios
            os: macos-latest
            path: haudiotagger/ios/Frameworks/haudiotagger.xcframework
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.ref_name }}
      - uses: ./.github/actions/setup_build
      - name: Install MUSL dependencies
        if: ${{ matrix.target == 'linux' }}
        run: |
          sudo apt install musl-tools
      - name: Build
        run: dart run cli build ${{ matrix.target }} -v
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.path }}

  publish_to_release:
    name: Publish Artifacts to Release
    needs: build_and_upload
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
      - name: Create Archives
        run: |
          tar -C linux -czvf linux.tar.gz .
          tar -C android -czvf android.tar.gz .
          tar -C windows -czvf windows.tar.gz .
          zip -j macos.zip macos/*
          cd ios && zip -r ios.zip ./* && cd .. && mv ios/ios.zip .
      - name: Add to Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            linux.tar.gz
            android.tar.gz
            windows.tar.gz
            macos.zip
            ios.zip
